services:
  rag_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_api_service
    ports:
      - "8090:8090"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8090 --reload
    restart: unless-stopped
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"